
CREATE TABLE IF NOT EXISTS drivers (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     full_name VARCHAR(100) NOT NULL,
                                     passport VARCHAR(10) NOT NULL,
                                     car_license_category VARCHAR(1),
                                     date_of_Birth  TIMESTAMP NOT NULL,
                                     driving_experience Integer,
                                     CONSTRAINT drivers_pk PRIMARY KEY (id),
                                     CONSTRAINT passport UNIQUE (passport),

                                  --   bill_id bigint
                                  --   references bills
                                   --  on delete cascade,

                                     car_id Integer


);

--DELETE FROM FILMS;
--ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;

CREATE TABLE IF NOT EXISTS bills (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             sum Integer,
                             CONSTRAINT bill_pk PRIMARY KEY (id),
                            driver_id   bigint  not null
                             references drivers
                             on delete cascade

);
--
-- --DELETE FROM users;
-- --ALTER TABLE users ALTER COLUMN ID RESTART WITH 1;
--
--
--
--
--CREATE TABLE IF NOT EXISTS cars_details (

  --  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

      --                               CONSTRAINT rate_pk PRIMARY KEY (id),
       --                              car_id bigint        not null
       --                                  references cars
        ---                                     on delete cascade,

       --                             detail_id   bigint        not null
       --                                  references details
       --                                      on delete cascade

--);